name: AutoUpdate
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Edge
        run: |
          sudo apt update
          sudo apt install -y microsoft-edge-stable

      - name: Install dependencies
        run: pip install selenium

      - name: Run script
        run: python3 spider.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Auto update"
